Onboarding Replication Policy using autorest
vidyadharijami/azure-powershell pull request #2
Opened 2023-06-01 11:40 UTC by ju993rn4ut

Get and Remove replicationpolicy commands completed

added default value to subscription id

new policy command

Update policy command and test units

## Description

- I have generated and made changes to all the Get, New, Remove, Update commands in Replication policy using Autorest.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2023-06-02 09:12 UTC, vidyadharijami requested changes
Please address the comments suggested.

2023-06-02 09:12 UTC, vidyadharijami commented on src/RecoveryServices/RecoveryServices.SiteRecovery.Autorest/ChangeLog.md
> +* First preview release for module Az.RecoveryServices. The cmdlets to support common scenarios of RecoveryServices like policies, fabrics, protection container, protection container mapping, enable
Remove these changes

2023-06-02 09:12 UTC, vidyadharijami commented on src/RecoveryServices/RecoveryServices.SiteRecovery.Autorest/README.md
> +- [Az.Accounts module](https://www.powershellgallery.com/packages/Az.Accounts/), version 2.2.3 or greater
Try with 2.7.5 version Az.Accounts itself

2023-06-02 09:12 UTC, vidyadharijami commented on src/RecoveryServices/RecoveryServices.SiteRecovery.Autorest/custom/Cmdlets/Policy/New-AzRecoveryServicesReplicationPolicy.ps1
> +                throw "For now we just support ReplicateAzureToAzure scenario, working on other scenarios"
Provided replication scenario is not supported. Only ReplicateAzureToAzure is applicable.

2023-06-02 09:12 UTC, vidyadharijami commented on src/RecoveryServices/RecoveryServices.SiteRecovery.Autorest/custom/Cmdlets/Policy/Remove-AzRecoveryServicesReplicationPolicy.ps1
> +	[OutputType([Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.Models.Api20230201.IJob])]
Indent left

2023-06-02 09:12 UTC, vidyadharijami commented on src/RecoveryServices/RecoveryServices.SiteRecovery.Autorest/custom/Cmdlets/Policy/Remove-AzRecoveryServicesReplicationPolicy.ps1
> +        # RsvRef
Remove

2023-06-02 09:12 UTC, vidyadharijami commented on src/RecoveryServices/RecoveryServices.SiteRecovery.Autorest/custom/Cmdlets/Policy/Remove-AzRecoveryServicesReplicationPolicy.ps1
> +
Remove this comment

2023-06-02 09:12 UTC, vidyadharijami commented on src/RecoveryServices/RecoveryServices.SiteRecovery.Autorest/custom/Cmdlets/Policy/Update-AzRecoveryServicesReplicationPolicy.ps1
> +            $replicationscenario=$ReplicationProviderSetting.ReplicationScenario
Align spaces

2023-06-02 09:12 UTC, vidyadharijami commented on src/RecoveryServices/RecoveryServices.SiteRecovery.Autorest/custom/Cmdlets/Policy/Update-AzRecoveryServicesReplicationPolicy.ps1
> +                throw "For now we just support ReplicateAzureToAzure scenario, working on other scenarios"
Change this as specified before

2023-06-02 09:12 UTC, vidyadharijami commented on src/RecoveryServices/RecoveryServices.SiteRecovery.Autorest/docs/Get-AzRecoveryServicesReplicationPolicy.md
> +### Example 1: Get all replication policies in a recovery services vault
List

2023-06-02 09:12 UTC, vidyadharijami commented on src/RecoveryServices/RecoveryServices.SiteRecovery.Autorest/test/Remove-AzRecoveryServicesReplicationPolicy.Tests.ps1
> +        {Remove-AzRecoveryServicesReplicationPolicy -Policy $obj -ResourceName $env.a2aVaultName -ResourceGroupName $env.a2aResourceGroupName -SubscriptionId $env.a2aSubscriptionId} | Should Not Thro
After remove cmdlet, Please add wait for job completion and check that it doesn't exist using Get cmdlet

2023-06-02 09:36 UTC, ju993rn4ut commented on src/RecoveryServices/RecoveryServices.SiteRecovery.Autorest/README.md
> +- [Az.Accounts module](https://www.powershellgallery.com/packages/Az.Accounts/), version 2.2.3 or greater
But whenever I run autorest, the version depreciates by itself.

2023-06-05 06:17 UTC, vidyadharijami approved these changes

2023-06-05 06:18 UTC, merged